'use client';
import { useEffect, useState, useRef } from 'react';
import { ArrowUpRight, ArrowRight, Plus, Search, MapPin, Bell, Recycle, LayoutGrid, Map, SlidersHorizontal, DoorOpen, Lamp, PanelsTopLeft, Refrigerator, Grid2X2, Shapes, Leaf, Clock, Check, Camera, LocateFixed, Truck, ChevronDown, Package, HeartHandshake, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { demoItems, categories, distance, type Item } from '@/lib/materials';

const icons=[LayoutGrid,PanelsTopLeft,Lamp,DoorOpen,Refrigerator,Grid2X2,Shapes];
const initialProfile={name:'',email:'',phone:'',role:'buyer',address:'Austin, TX',lat:30.2672,lng:-97.7431,radius:20,preferences:categories.slice(1)};
const blank={title:'',description:'',category:'Other',material:'',condition:'Good',address:'',lat:30.2672,lng:-97.7431,photo:''};
export default function Salvage({mode,initialAccount}:{mode:string;initialAccount:any}){
 const [items,setItems]=useState<Item[]>(demoItems),[live,setLive]=useState(false),[profile,setProfile]=useState<typeof initialProfile>({...initialProfile,...initialAccount}),[registered,setRegistered]=useState(true),[view,setView]=useState(mode==='contractor'?'My listings':'Explore'),[category,setCategory]=useState('All materials'),[search,setSearch]=useState(''),[sort,setSort]=useState('nearest'),[layout,setLayout]=useState('grid'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Item|null>(null),[draft,setDraft]=useState(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[notes,setNotes]=useState<any[]>([]),[aiNote,setAiNote]=useState(''),[donation,setDonation]=useState({nonprofit:'',value:''});
 const editing=useRef(false); editing.current=!!modal;
 const notify=(s:string)=>setMessage(s);
 async function api(action:string,data:any={}){const res=await fetch('/api/salvage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})}); const result:any=await res.json(); if(!res.ok)throw Error(result.error||'Please try again.');return result;}
 async function refresh(){try{const r=await fetch('/api/salvage');if(!r.ok)return;const d:any=await r.json();setLive(true);setItems(d.items.length?d.items:demoItems);if(d.profile){if(!editing.current)setProfile(d.profile);setRegistered(true);}setNotes(d.notifications||[]);}catch{}}
 useEffect(()=>{refresh();const t=setInterval(refresh,15000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),6500);return()=>clearTimeout(t);}},[message]);
 function location(target:'profile'|'draft'){if(!navigator.geolocation){notify('Location is unavailable. Enter a pickup address.');return;}navigator.geolocation.getCurrentPosition(async p=>{const coords={lat:p.coords.latitude,lng:p.coords.longitude};let address=`${coords.lat.toFixed(4)}, ${coords.lng.toFixed(4)}`;try{const r=await fetch(`/api/location?lat=${coords.lat}&lng=${coords.lng}`);const d:any=await r.json();if(d.address)address=d.address;}catch{};if(target==='profile')setProfile(v=>({...v,...coords,address}));else setDraft(v=>({...v,...coords,address}));},()=>notify('Location access was declined. You can enter an address instead.'));}
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(modal==='location'&&!registered){const res=await fetch('/api/location?q='+encodeURIComponent(profile.address));const found:any=await res.json();if(!res.ok)throw Error(found.error);setProfile(v=>({...v,...found}));setModal('');return;}const d=await api('profile',{profile});if(!editing.current)setProfile(d.profile);setRegistered(true);setModal('');notify('Your pickup preferences are saved.');await refresh();}catch(e:any){notify(e.message);}finally{setBusy(false);}}
 async function photo(file:File|undefined){if(!file)return;if(file.size>10*1024*1024){notify('Choose a photo smaller than 10 MB.');return;}setBusy(true);setAiNote('Reading your photo…');try{const image=await new Promise<string>((resolve,reject)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');const ratio=Math.min(1,1280/Math.max(im.width,im.height));c.width=im.width*ratio;c.height=im.height*ratio;c.getContext('2d')!.drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.85));URL.revokeObjectURL(im.src);};im.onerror=reject;im.src=URL.createObjectURL(file);});setDraft(v=>({...v,photo:image}));const d=await api('analyze',{image});setDraft(v=>({...v,...d}));setAiNote('Photo analyzed. Check the details, then publish.');}catch(e:any){setAiNote(e.message||'We couldn’t read that photo. Fill in the details below.');}finally{setBusy(false);}}
 async function publish(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('publish',{listing:draft});setModal('');setDraft(blank);notify('Listed! Nearby buyers can now claim your item.');setView('My listings');await refresh();}catch(e:any){notify(e.message);}finally{setBusy(false);}}
 async function claim(item:Item){if(item.demo){notify('This is a sample listing. Real listings can be claimed after you create a buyer profile.');return;}if(!registered){setSelected(null);setModal('profile');return;}setBusy(true);try{const d=await api('claim',{id:item.id});setSelected({...item,...d.item});notify('It’s yours! Contact the contractor to arrange pickup.');await refresh();}catch(e:any){notify(e.message);}finally{setBusy(false);}}
 const filtered=items.filter(i=>(view==='My listings'?i.mine:view==='My pickups'?i.claimedMine:i.status==='available')&&(category==='All materials'||i.category===category)&&`${i.title} ${i.material} ${i.description}`.toLowerCase().includes(search.toLowerCase())&&(view!=='Explore'||distance(profile,i)<=profile.radius)).sort((a,b)=>sort==='newest'?b.created_at-a.created_at:distance(profile,a)-distance(profile,b));
 const openAdd=()=>{if(!registered||profile.role!=='contractor'){setModal('profile');setProfile(v=>({...v,role:'contractor'}));notify('Save your contractor profile once, then start listing.');}else{setDraft({...blank,address:profile.address,lat:profile.lat,lng:profile.lng});setAiNote('');setModal('add');location('draft');}};
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Recycle size={27}/></span>salvage<span className="brand-dot">.</span></a><nav>{(mode==='contractor'?['My listings']:['Explore','My pickups']).map(v=><button key={v} className={view===v?'nav-active':''} onClick={()=>{setView(v);setCategory('All materials');}}>{v}</button>)}</nav><div className="header-actions"><button className="icon-button notification" aria-label="Notifications" onClick={()=>setModal('notifications')}><Bell size={21}/>{notes.some(n=>!n.read_at)&&<i/>}</button><button className="avatar" onClick={()=>setModal('profile')} aria-label="Your profile">{profile.name?profile.name.split(' ').map(s=>s[0]).slice(0,2).join(''):'JD'}</button><a className="signout-link" href="/signout-with-chatgpt?return_to=%2Flogin" target="_top">Log out</a>{mode==='contractor'&&<button className="primary add-top" onClick={openAdd}><Plus size={19}/> Add item</button>}</div></header>
  <main className="workspace"><div className="page-heading"><div><div className="eyebrow"><span/> {mode==='contractor'?'YOUR CONTRACTOR WORKSPACE':'THE LOCAL MATERIAL EXCHANGE'}</div><h1>{view==='Explore'?'Good materials. Another life.':view==='My listings'?'Less waste. More possibility.':'Your next great find.'}</h1><p>{view==='Explore'?'Find reusable building materials around the corner. Save them from the dumpster.':view==='My listings'?'Everything you’ve put back to work, in one place.':'Arrange a pickup and give these materials a new home.'}</p></div><button className="location-button" onClick={()=>setModal('location')}><MapPin size={18}/><span>{profile.address}<small>Within {profile.radius} miles</small></span><ChevronDown size={16}/></button></div>
  {mode==='contractor'?<div className="contractor-action"><div><span className="contractor-camera"><Camera size={28}/></span><h2>Out with the old.<br/>On to its next project.</h2><p>Take a photo. Confirm the details. We’ll find it a new home.</p></div><button className="primary" onClick={openAdd}><Plus size={22}/> Add an item</button></div>:<div className="intro-strip"><div className="strip-icon"><Leaf size={25}/></div><div><strong>Still useful. Just needs a new home.</strong><span>All materials are free. You handle the pickup.</span></div><div className="strip-right"><button onClick={()=>setModal('profile')}>Your buyer preferences <ArrowUpRight size={18}/></button></div></div>}
  <div className="search-row"><div className="search-box"><Search size={21}/><input aria-label="Search materials" placeholder="Search cabinets, doors, tile, and more…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={17}/></button>}</div><button className="filter-button" onClick={()=>setModal('location')}><SlidersHorizontal size={18}/> Filters <span>{profile.radius} mi</span></button></div>
  <div className="category-row">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} onClick={()=>setCategory(c)} className={category===c?'category active':'category'}><Icon size={18}/>{c}</button>;})}</div>
  <div className="results-bar"><div><h2>{view==='Explore'?'Available nearby':view}</h2><span>{filtered.length} materials <span className="live-dot"/> {items.some(i=>i.demo)?'Sample listings':'Updated live'}</span></div><div className="results-options"><Select value={sort} onValueChange={v=>setSort(v||'nearest')}><SelectTrigger className="sort-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="nearest">Nearest first</SelectItem><SelectItem value="newest">Newest first</SelectItem></SelectContent></Select><Tabs value={layout} onValueChange={setLayout}><TabsList className="view-toggle"><TabsTrigger value="grid" aria-label="Grid view"><LayoutGrid size={17}/></TabsTrigger><TabsTrigger value="map" aria-label="Map view"><Map size={17}/></TabsTrigger></TabsList></Tabs></div></div>
  {layout==='map'&&<div className="map-panel"><iframe title="Map of your pickup area" src={`https://www.openstreetmap.org/export/embed.html?bbox=${profile.lng-.2}%2C${profile.lat-.14}%2C${profile.lng+.2}%2C${profile.lat+.14}&layer=mapnik&marker=${profile.lat}%2C${profile.lng}`}/><div className="map-caption"><MapPin size={17}/> Your search area · Choose an item below for its pickup area.</div></div>}
  <div className="material-grid">{filtered.map(item=><button className="material-card" key={item.id} onClick={()=>setSelected(item)}><div className="card-photo"><img src={item.photo} alt={item.title}/><span className="free-badge">{item.status==='available'?'FREE':item.status.toUpperCase()}</span><span className="photo-arrow"><ArrowUpRight size={18}/></span></div><div className="card-body"><div className="card-kicker"><span>{item.category}</span><span className={`condition ${item.condition.toLowerCase()}`}><i/>{item.condition}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="card-meta"><span><MapPin size={14}/>{distance(profile,item).toFixed(1)} mi · {item.area||'Nearby'}</span><span><Clock size={13}/>{item.demo?item.age:timeAgo(item.created_at)}</span></div><div className="card-bottom"><span><span className="mini-avatar">{item.owner_name?.slice(0,1)||'S'}</span>{item.owner_name||'Local contractor'}</span><span className="pickup-text"><Truck size={14}/>{item.status==='available'?'Pickup ready':item.status==='claimed'?'Claimed':'Donated'}</span></div></div></button>)}</div>
  {!filtered.length&&<div className="empty-state"><Package size={36}/><h3>{view==='Explore'?'No materials in this search yet.':'Nothing here just yet.'}</h3><p>{view==='Explore'?'Try another category or expand your pickup radius.':'Explore nearby materials or list something worth saving.'}</p><button className="primary" onClick={()=>{setCategory('All materials');setSearch('');if(view==='Explore')setModal('location');else if(mode==='contractor')openAdd();else setView('Explore');}}> {view==='Explore'?'Adjust search area':mode==='contractor'?'List your first item':'Explore materials'} <ArrowRight size={17}/></button></div>}
  <div className="bottom-note"><Recycle size={17}/><span>A second life for materials. A little less in the landfill.</span></div>
  </main><footer><a className="footer-brand" href="/">salvage.</a><span>Built for the next build.</span><span className="footer-right">Good for your project. Better for the planet. <Leaf size={14}/></span></footer>
  {mode==='contractor'&&<button className="mobile-add primary" onClick={openAdd}><Plus size={22}/> Add item</button>}
  <Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('');}}><DialogContent className="salvage-modal"><DialogTitle>{modal==='add'?'Give it another life.':modal==='notifications'?'Your updates':modal==='donate'?'Record a nonprofit donation':modal==='profile'?'Your Salvage profile':'Your pickup area'}</DialogTitle><DialogDescription>{modal==='add'?'One photo. A few details. Out of the dumpster.':modal==='notifications'?'New matches and pickup activity appear here.':modal==='donate'?'Save the details and download a donation record.':modal==='profile'?'Set this up once. Get back to the job.':'Find materials close enough to collect.'}</DialogDescription>
   {modal==='add'&&<form onSubmit={publish} className="form-stack"><label className="photo-upload">{draft.photo?<img src={draft.photo} alt="Your item"/>:<><Camera size={30}/><strong>Take or upload a photo</strong><span>We’ll fill in the details for you</span></>}<input type="file" accept="image/*" onChange={e=>photo(e.target.files?.[0])} disabled={busy}/></label>{aiNote&&<p className="ai-note" role="status">{aiNote}</p>}<label>Title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="form-two"><label>Category<Select value={draft.category} onValueChange={v=>setDraft({...draft,category:v||'Other'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.slice(1).map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label><label>Condition<Select value={draft.condition} onValueChange={v=>setDraft({...draft,condition:v||'Good'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Excellent','Good','Fair','Poor'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label></div><label>Material<input required value={draft.material} onChange={e=>setDraft({...draft,material:e.target.value})}/></label><label>Description<textarea required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Pickup address<div className="input-action"><input required value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/><button type="button" aria-label="Use current location" onClick={()=>location('draft')}><LocateFixed size={20}/></button></div></label><small>Exact address and your contact details are shared only with the buyer who claims it.</small><button className="primary full" disabled={busy||!draft.photo}>{busy?'Working…':'Publish free listing'} <ArrowRight size={18}/></button></form>}
   {(modal==='profile'||modal==='location')&&<form onSubmit={saveProfile} className="form-stack">{modal==='profile'&&<><div className="account-role"><Check size={17}/> {mode==='contractor'?'Contractor':'Buyer'} account</div><label>Name or organization<input required value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><div className="form-two"><label>Email<input type="email" required value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label>Phone<input type="tel" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label></div></>}<label>Location or ZIP code<div className="input-action"><input required value={profile.address} onChange={e=>setProfile({...profile,address:e.target.value})}/><button type="button" aria-label="Use current location" onClick={()=>location('profile')}><LocateFixed size={20}/></button></div></label><label>Pickup radius <strong>{profile.radius} miles</strong><Slider value={[profile.radius]} onValueChange={v=>setProfile({...profile,radius:Array.isArray(v)?v[0]:v})} min={1} max={100} step={1}/></label><label>Notify me about</label><div className="preference-grid">{categories.slice(1).map(c=><label key={c}><Checkbox checked={profile.preferences.includes(c)} onCheckedChange={v=>setProfile({...profile,preferences:v?[...profile.preferences,c]:profile.preferences.filter(x=>x!==c)})}/>{c}</label>)}</div><button disabled={busy} className="primary full">{busy?'Saving…':'Save preferences'}<Check size={18}/></button>{!registered&&<a className="signin-link" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT to save your profile</a>}</form>}
   {modal==='notifications'&&<div className="notification-list">{notes.length?notes.map(n=><button key={n.id} onClick={async()=>{await api('read',{id:n.id});setModal('');const i=items.find(i=>i.id===n.listing_id);if(i)setSelected(i);refresh();}}><Bell size={20}/><span>{n.message}<small>{timeAgo(n.created_at)}</small></span></button>):<div className="empty-state"><Bell size={30}/><h3>You’re all caught up.</h3><p>Save your categories and radius to receive matching listings here.</p><button className="primary" onClick={()=>setModal('profile')}>Set preferences</button></div>}</div>}
   {modal==='donate'&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('donate',{id:selected!.id,...donation});downloadReceipt(selected!,donation);setModal('');setSelected(null);refresh();notify('Donation recorded and receipt downloaded.');}catch(e:any){notify(e.message);}finally{setBusy(false);}}}><label>Nonprofit name<input required value={donation.nonprofit} onChange={e=>setDonation({...donation,nonprofit:e.target.value})}/></label><label>Your estimated value (USD)<input type="number" min="0" step="0.01" required value={donation.value} onChange={e=>setDonation({...donation,value:e.target.value})}/></label><p className="muted">This is your donation record, not an acknowledgment issued by the nonprofit. Keep the nonprofit’s receipt with it.</p><button className="primary" disabled={busy}>Record & download <HeartHandshake size={18}/></button></form>}
  </DialogContent></Dialog>
  <Dialog open={!!selected&&modal!=='donate'} onOpenChange={o=>{if(!o)setSelected(null);}}><DialogContent className="salvage-modal item-modal"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.category} · {selected?.material} · {selected?.condition} condition</DialogDescription>{selected&&<><img className="detail-photo" src={selected.photo} alt={selected.title}/><div className="detail-free">Free <span>Give it a new home.</span></div><p>{selected.description}</p><div className="detail-location"><MapPin size={20}/><span>{selected.address||`${selected.area||'Local pickup'} · ${distance(profile,selected).toFixed(1)} miles away`}<small>{selected.address?'Coordinate a pickup time before visiting.':'Exact pickup address is shared after claiming.'}</small></span></div>{selected.contact&&<div className="contact-card"><strong>{selected.contact.name}</strong><a href={`mailto:${selected.contact.email}`}>{selected.contact.email}</a>{selected.contact.phone&&<a href={`tel:${selected.contact.phone}`}>{selected.contact.phone}</a>}</div>}{selected.demo&&<p className="sample-note">Sample listing · This shows what materials will look like on Salvage.</p>}{selected.status==='available'&&!selected.mine&&<button className="primary full" disabled={busy} onClick={()=>claim(selected)}>Claim for pickup <ArrowRight size={19}/></button>}{selected.mine&&selected.status!=='donated'&&<button className="primary full" onClick={()=>setModal('donate')}><HeartHandshake size={19}/> Mark donated to nonprofit</button>}{selected.status!=='available'&&<p className="ai-note"><Check size={17}/> {selected.status==='claimed'?'Claimed — arrange pickup directly.':'Donated — another life made possible.'}</p>}</>}</DialogContent></Dialog>
  {message&&<div className="toast" role="status"><span>{message}</span><button onClick={()=>setMessage('')} aria-label="Dismiss"><X size={18}/></button></div>}
 </div>;
}
function timeAgo(ts:number){const mins=Math.max(1,Math.round((Date.now()-ts)/60000));return mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ago`:`${Math.floor(mins/1440)}d ago`;}
function downloadReceipt(i:Item,d:{nonprofit:string,value:string}){const text=`SALVAGE — DONATION RECORD\n\nItem: ${i.title}\nDescription: ${i.description}\nEstimated value (donor provided): $${Number(d.value).toFixed(2)}\nNonprofit: ${d.nonprofit}\nDate: ${new Date().toLocaleDateString()}\nListing: ${i.id}\n\nThis record is not a nonprofit acknowledgment or a valuation. Retain the receiving organization's receipt.`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`salvage-donation-${i.id}.txt`;a.click();URL.revokeObjectURL(url);}



