export const categories=['All materials','Cabinetry','Fixtures','Doors','Appliances','Tile & flooring','Other'];
export type Item={id:string;title:string;description:string;category:string;material:string;condition:string;photo:string;lat:number;lng:number;area?:string;status:string;created_at:number;owner_name?:string;demo?:boolean;age?:string;mine?:boolean;claimedMine?:boolean;address?:string;contact?:{name:string;email:string;phone:string}};
export function distance(a:{lat:number;lng:number},b:{lat:number;lng:number}){const r=Math.PI/180;const dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;return 3958.8*2*Math.atan2(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2),Math.sqrt(1-(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2)));}
export const demoItems:Item[]=[
{id:'sample-1',title:'Solid oak kitchen cabinets',description:'A complete set, ready for a fresh start.',category:'Cabinetry',material:'Oak',condition:'Good',photo:'https://images.ctfassets.net/9aljq1ivr2md/6etNgU5eC3vTbqnoguD6S0/26ee68446ef583ddb0c677d437bf18e0/oak-kitchen-cabinets.jpg?bg=transparent&fl=progressive&fm=jpg&h=525&q=50&w=1000',lat:30.275,lng:-97.75,area:'Clarksville',status:'available',created_at:6,owner_name:'Eastside Renovations',demo:true,age:'12m ago'},
{id:'sample-2',title:'Reclaimed solid wood door',description:'Original character. Hardware included.',category:'Doors',material:'Wood',condition:'Good',photo:'https://mongers.s3.amazonaws.com/uploads/c/product/image/image/8427/product_standard_DSC_5827.JPG',lat:30.282,lng:-97.735,area:'Hyde Park',status:'available',created_at:5,owner_name:'Cedar & Stone Co.',demo:true,age:'28m ago'},
{id:'sample-3',title:'Brass dome pendant light',description:'Warm brass finish, with ceiling fitting.',category:'Fixtures',material:'Brass',condition:'Excellent',photo:'https://www.cultfurniture.com/cdn/shop/files/CF_EN98744_1.webp?v=1746108983&width=1200',lat:30.24,lng:-97.757,area:'Bouldin Creek',status:'available',created_at:4,owner_name:'South Austin Remodel',demo:true,age:'45m ago'},
{id:'sample-4',title:'White ceramic basin',description:'Clean lines. No visible chips or cracks.',category:'Fixtures',material:'Ceramic',condition:'Excellent',photo:'https://media.adeo.com/mkp/3ed2538ac36651893587dab00b344cfc/media.jpg',lat:30.303,lng:-97.76,area:'Rosedale',status:'available',created_at:3,owner_name:'Miller Contracting',demo:true,age:'1h ago'},
{id:'sample-5',title:'Patterned ceramic floor tile',description:'Leftover tiles for your next small project.',category:'Tile & flooring',material:'Ceramic',condition:'Excellent',photo:'https://www.cravendunnill.co.uk/media/catalog/product/cache/13ba06762dbf08afc372e6c8f8232901/r/e/ren636-ornata-cervera-2_1.jpeg',lat:30.315,lng:-97.724,area:'North Loop',status:'available',created_at:2,owner_name:'Groundwork Builders',demo:true,age:'2h ago'},
{id:'sample-6',title:'Stainless steel dishwasher',description:'A kitchen upgrade with life left in it.',category:'Appliances',material:'Stainless steel',condition:'Good',photo:'https://cdn.shopify.com/s/files/1/0573/3207/2636/files/SMS4EMI06G-1_540x.jpg?v=1723535279',lat:30.22,lng:-97.79,area:'Westgate',status:'available',created_at:1,owner_name:'Greenline Construction',demo:true,age:'3h ago'}
];

